package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"

	"github.com/Nutchanon28/file-sharing-system/graph/model"
	"github.com/google/uuid"
)

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, newSharedFile model.NewSharedFile) (*model.SharedFile, error) {
	id := uuid.New().String()

	sharedFile := model.SharedFile{
		ID:        id,
		Status:    newSharedFile.Status,
		Name:      newSharedFile.Name,
		FileURL:   "some test",
		CreatedBy: nil,
		// FileURL:   newSharedFile.File,
		// CreatedBy: newSharedFile.UserID,
	}

	r.SharedFilesList = append(r.SharedFilesList, &sharedFile)

	return &sharedFile, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Departments is the resolver for the departments field.
func (r *queryResolver) Departments(ctx context.Context) ([]*model.Department, error) {
	panic(fmt.Errorf("not implemented: Departments - departments"))
}

// Faculties is the resolver for the faculties field.
func (r *queryResolver) Faculties(ctx context.Context) ([]*model.Faculty, error) {
	panic(fmt.Errorf("not implemented: Faculties - faculties"))
}

// SharedFiles is the resolver for the sharedFiles field.
func (r *queryResolver) SharedFiles(ctx context.Context) ([]*model.SharedFile, error) {
	fmt.Println("get all shared files ran")
	return r.SharedFilesList, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}

// GetDepartment is the resolver for the getDepartment field.
func (r *queryResolver) GetDepartment(ctx context.Context, id string) (*model.Department, error) {
	panic(fmt.Errorf("not implemented: GetDepartment - getDepartment"))
}

// GetFaculty is the resolver for the getFaculty field.
func (r *queryResolver) GetFaculty(ctx context.Context, id string) (*model.Faculty, error) {
	panic(fmt.Errorf("not implemented: GetFaculty - getFaculty"))
}

// GetSharedFile is the resolver for the getSharedFile field.
func (r *queryResolver) GetSharedFile(ctx context.Context, id string) (*model.SharedFile, error) {
	panic(fmt.Errorf("not implemented: GetSharedFile - getSharedFile"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
